made techrity-tmp22 week-1 & week-2 projects
techrityorg/Mentorship pull request #16
Opened 2022-09-04 18:59 UTC by codingkush

I have made week-1 and week-2 projects of techrity-tmp22....

2022-09-05 10:53 UTC, siddhi-244 requested changes
Make a folder inside tmp 2022 folder by your name. And make sure you add readme as I suggested on slack. Please try to attend the sessions carefully,  I have explained everything there

2022-09-30 14:32 UTC, siddhi-244 requested changes
Please check the merged project readme ! Change your readme accordingly

2022-10-11 07:20 UTC, codingkush commented
Ok, I will check.

On Fri, Sep 30, 2022, 8:03 PM Siddhi Bhanushali ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please check the merged project readme ! Change your readme accordingly
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/techrityorg/Mentorship/pull/16#pullrequestreview-1126921701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASY3TWDPYVLQ6JICDKLXLJLWA322LANCNFSM6AAAAAAQEOBHZ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 07:21 UTC, codingkush commented
Ok ..

On Mon, Sep 5, 2022, 4:24 PM Siddhi Bhanushali ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Make a folder inside tmp 2022 folder by your name. And make sure you add
> readme as I suggested on slack. Please try to attend the sessions
> carefully, I have explained everything there
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/techrityorg/Mentorship/pull/16#pullrequestreview-1096263092>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASY3TWAL6GCI3XN6FXKCUW3V4XGMRANCNFSM6AAAAAAQEOBHZ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-18 21:00 UTC, Duffigoogle approved these changes

2025-07-30 13:42 UTC, closed without merging